# How to Do Mathematics Easily - Intro to Deep Learning #4

Source: https://www.youtube.com/watch?v=N4gDikiec8E

## Imports

In [1]:
import numpy as np

## Initialize

### Input Data

In [2]:
x = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

In [3]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


### Output Data

In [4]:
y = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [5]:
print(y)

[[0]
 [1]
 [1]
 [0]]


### Build Model

In [6]:
num_epocs = 600000 #60000

#### Initial Weights

In [7]:
syn0 = 2 * np.random.random((3,4)) - 1
syn1 = 2 * np.random.random((4,1)) - 1

-1 < weight < 1 

In [8]:
print(syn0)

[[-0.31973978  0.78466758 -0.96462947 -0.22055315]
 [ 0.69496398  0.02818436 -0.68074898  0.6525262 ]
 [-0.14419298  0.33170207  0.93505435 -0.13729155]]


Fully Connected Layer

In [9]:
print(syn1)

[[ 0.59128255]
 [-0.58932609]
 [-0.3238463 ]
 [ 0.73169484]]


Size of our output

### Non linear sigmoid function

In [10]:
def nonlin(x, deriv=False):
    
    #if we need the slope aka gradient
    if (deriv == True):
        return x * (1 - x)
    
    return 1 / (1 + np.exp(-x))

## Train Model

In [11]:
for j in range(num_epocs):
    #feed forward through layers 0,1, and 2
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    #propagate it forward to layer 2
    l2 = nonlin(np.dot(l1, syn1))
    #l2 output is our prediction
    
    #how much did we miss the target value?
    l2_error = y - l2
    
    if (j % 100000) == 0:
        print('Error : ' + str(np.mean(np.abs(l2_error))))
        
    #in what direction is the target value?
    l2_delta = l2_error * nonlin(l2, deriv=True)
    
    #back propagation
    
    #how much did each l1 value contribute to l2 error?
    l1_error = l2_delta.dot(syn1.T) #t is the transpose
    
    l1_delta = l1_error * nonlin(l1, deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error : 0.500434594091
Error : 0.00302613113254
Error : 0.00211537488967
Error : 0.0017175237155
Error : 0.001482033796
Error : 0.00132206636347
